Grabbing training data...
Grabbing testing data...
Training model...
/Users/kelseydoerksen/opt/anaconda3/envs/landslides-unet/lib/python3.10/site-packages/torch/cuda/amp/grad_scaler.py:126: UserWarning: torch.cuda.amp.GradScaler is enabled, but CUDA is not available.  Disabling.
  warnings.warn(
Training EPOCH 0:
Running Test set...
> [0;32m/Users/kelseydoerksen/code/landslide-forecast-nepal/unet/predict.py[0m(35)[0;36mpredict[0;34m()[0m
[0;32m     34 [0;31m[0;34m[0m[0m
[0m[0;32m---> 35 [0;31m    [0mloss_criterion[0m [0;34m=[0m [0mnn[0m[0;34m.[0m[0mBCEWithLogitsLoss[0m[0;34m([0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[0;32m     36 [0;31m    [0mbce_score[0m [0;34m=[0m [0;36m0[0m[0;34m[0m[0;34m[0m[0m
[0m
19
*** AttributeError: 'DataLoader' object has no attribute 'shape'
<torch.utils.data.dataloader.DataLoader object at 0x14bf0e7a0>
torch.Size([10, 1, 60, 100])
torch.Size([10, 1, 60, 100])
torch.Size([10, 1, 60, 100])
torch.Size([10, 1, 60, 100])
torch.Size([10, 1, 60, 100])
torch.Size([10, 1, 60, 100])
torch.Size([10, 1, 60, 100])
torch.Size([10, 1, 60, 100])
torch.Size([10, 1, 60, 100])
torch.Size([10, 1, 60, 100])
torch.Size([10, 1, 60, 100])
torch.Size([10, 1, 60, 100])
torch.Size([10, 1, 60, 100])
torch.Size([10, 1, 60, 100])
torch.Size([10, 1, 60, 100])
torch.Size([10, 1, 60, 100])
torch.Size([10, 1, 60, 100])
torch.Size([10, 1, 60, 100])
torch.Size([7, 1, 60, 100])
Traceback (most recent call last):
  File "/Users/kelseydoerksen/code/landslide-forecast-nepal/unet/run_pipeline.py", line 162, in <module>
    predict(trained_model, landslide_test_dataset, experiment, save_dir, device=device,
  File "/Users/kelseydoerksen/code/landslide-forecast-nepal/unet/predict.py", line 35, in predict
    precision = 0
  File "/Users/kelseydoerksen/code/landslide-forecast-nepal/unet/predict.py", line 35, in predict
    precision = 0
  File "/Users/kelseydoerksen/opt/anaconda3/envs/landslides-unet/lib/python3.10/bdb.py", line 90, in trace_dispatch
    return self.dispatch_line(frame)
  File "/Users/kelseydoerksen/opt/anaconda3/envs/landslides-unet/lib/python3.10/bdb.py", line 115, in dispatch_line
    if self.quitting: raise BdbQuit
bdb.BdbQuit

If you suspect this is an IPython 8.30.0 bug, please report it at:
    https://github.com/ipython/ipython/issues
or send an email to the mailing list at ipython-dev@python.org

You can print a more detailed traceback right now with "%tb", or use "%debug"
to interactively debug it.

Extra-detailed tracebacks for bug-reporting purposes can be enabled via:
    %config Application.verbose_crash=True
